language: generic

branches:
  only:
  - dev-robin

env:
  global:
  - URL_DA_ROBIN: ec2-54-229-211-245.eu-west-1.compute.amazonaws.com

addons:
  ssh_known_hosts:
  - ec2-54-229-211-245.eu-west-1.compute.amazonaws.com # robin

before_deploy:
- openssl aes-256-cbc -K $encrypted_459d78462fa3_key -iv $encrypted_459d78462fa3_iv
  -in deploy_docassemble.enc -out /tmp/deploy_rsa_da -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa_da
- ssh-add /tmp/deploy_rsa_da

deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/deploy.sh $URL_DA_ROBIN
    on:
      branch: dev-robin